# -*- coding: utf-8 -*-
"""tienxulydulieu.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PbnazwtpoZpk_usUa-ZPoNDKvNVqiH3-
"""

# =============================================================================
# PREPROCESSING PIPELINE
# 2.3.1 Lowercase
# 2.3.2 Remove punctuation
# 2.3.3 Remove URL
# =============================================================================

import pandas as pd
import re
import string

# =============================================================================
# 1. LOAD DỮ LIỆU
# =============================================================================

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Shoes_Train_Data.xlsx')

# Chọn 10 dòng đầu để minh họa
sample_df = df[["Review"]].head(10).copy()

print("=" * 70)
print("BƯỚC 0 — DỮ LIỆU GỐC")
print("=" * 70)

display(sample_df)


# =============================================================================
# 2.3.1 LOWERCASE
# =============================================================================

sample_df["Review_Lowercase"] = (
    sample_df["Review"]
    .astype(str)
    .str.lower()
)

print("=" * 70)
print("BƯỚC 1 — LOWERCASE")
print("=" * 70)

display(sample_df[["Review", "Review_Lowercase"]])


# =============================================================================
# 2.3.3 REMOVE URL
# =============================================================================

url_pattern = r'https?://\S+|www\.\S+'

sample_df["Review_NoURL"] = (
    sample_df["Review_Lowercase"]
    .str.replace(url_pattern, '', regex=True)
)

print("=" * 70)
print("BƯỚC 2 — REMOVE URL")
print("=" * 70)

display(sample_df[["Review_Lowercase", "Review_NoURL"]])


# =============================================================================
# 2.3.2 REMOVE PUNCTUATION
# =============================================================================

punct_table = str.maketrans('', '', string.punctuation)

sample_df["Review_Preprocessed"] = (
    sample_df["Review_NoURL"]
    .str.translate(punct_table)
    .str.replace(r'\s+', ' ', regex=True)
    .str.strip()
)

print("=" * 70)
print("BƯỚC 3 — REMOVE PUNCTUATION")
print("=" * 70)

display(sample_df[["Review_NoURL", "Review_Preprocessed"]])


# =============================================================================
# 5. BẢNG MINH HỌA TRƯỚC / SAU PREPROCESSING
# =============================================================================

print("=" * 70)
print("BƯỚC 4 — BẢNG MINH HỌA TRƯỚC VÀ SAU PREPROCESSING")
print("=" * 70)

display(sample_df[
    [
        "Review",
       "Review_Lowercase",
        "Review_NoURL",
        "Review_Preprocessed"
    ]
])