# -*- coding: utf-8 -*-
"""Xử lý dữ liệu rác, xóa emoji và chuẩn hóa từ vựng.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kdyelM0po59-1qsz4k9Yoj7cjG9sEJfa
"""

!pip install pandas numpy openpyxl

import re
import pandas as pd

# 1. Đọc dữ liệu tập TEST
file_path = "Shoes_Test_Data.xlsx"
df = pd.read_excel(file_path)

# 1. Hàm bắt cứng chuỗi rác dựa trên Blacklist ký tự gõ càn
def is_strictly_gibberish(text):
    if not isinstance(text, str) or not text.strip():
        return True
    text_clean = text.lower().strip()
    gibberish_blacklist = [
        r"sidbd",
        r"síbd",
        r"gti",
        r"dbd",
        r"sbd",
        r"hhd",
        r"shs",
        r"jxj",
        r"hjh",
        r"([a-z])\1{4,}",  # Spam chữ dài xxxxx, jjjjj
    ]
    for pattern in gibberish_blacklist:
        if re.search(pattern, text_clean):
            return True
    return False


# 2. Định nghĩa danh sách các tệp dữ liệu đầu vào
files = {
    "Train": "Shoes_Train_Data.xlsx",
    "Test": "Shoes_Test_Data.xlsx",
    "Validate": "Shoes_Validate_Data.xlsx",
}

print("Quy trình quét và xóa bỏ dữ liệu rác")

filtered_dataframes = {}

for name, path in files.items():
    # Change pd.read_csv to pd.read_excel
    df_raw = pd.read_excel(path)
    total_raw = len(df_raw)

    # THỰC HIỆN XÓA BỎ các dòng rác bằng dấu ngã (~)
    df_filtered = df_raw[~df_raw["Review"].apply(is_strictly_gibberish)].copy()
    total_filtered = len(df_filtered)

    filtered_dataframes[name] = df_filtered
    print(
        f"✅ Tập [{name:8}]: Gốc: {total_raw} dòng -> Đã xóa: {total_raw - total_filtered} dòng rác -> Còn lại: {total_filtered} dòng."
    )

# Bảng hiển thị trước và sau khi xóa rác
# Change pd.read_csv to pd.read_excel
df_test_raw = pd.read_excel(files["Test"]).head(5)
df_test_raw["Trạng thái sau Quy trình 1"] = df_test_raw["Review"].apply(
    lambda x: "🗑️ ĐÃ XÓA BỎ (Rác)" if is_strictly_gibberish(x) else "✅ GIỮ LẠI (Sạch)"
)

pd.set_option("display.max_colwidth", 55)
print("\n Bảng hiển thị kết quả trước và sau khi xóa rác:")
print(
    df_test_raw[["Review", "Trạng thái sau Quy trình 1"]].to_markdown(
        index=True
    )
)

# Quy trình xóa Emoji/Icon và Chuẩn hóa văn bản

def clean_and_normalize_review(text):
    if not isinstance(text, str):
        return ""

    text = text.lower()
    # 1. Xóa Emoji, Icon (Chỉ giữ lại chữ Tiếng Việt, số và dấu chấm, phẩy)
    text = re.sub(r"[^\w\s,.]|_", "", text, flags=re.UNICODE)

    # 2. Từ điển chuẩn hóa từ viết tắt TMĐT Gen Z
    teencode_dict = {
        r"\bsp\b|\bshp\b": "sản phẩm",
        r"\bshb\b|\bshop\b": "cửa hàng",
        r"\bk\b|\bko\b|\bkhg\b|\bkh\b": "không",
        r"\bmn\b|\bmng\b": "mọi người",
        r"\bsz\b": "size",
        r"\bđc\b|\bdc\b": "được",
        r"\bokie\b|\bok\b|\boke\b": "ổn",
        r"\bnhma\b": "nhưng mà",
        r"\bvs\b": "với",
        r"\bđg\b": "đang",
        r"\bbth\b|\bbt\b": "bình thường",
        r"\bqá\b|\bqa\b": "quá",
        r"\btks\b|\bthanks\b": "cảm ơn",
        r"\bgiầy\b": "giày",
        r"\bđt\b": "đặt",
    }
    for pattern, replacement in teencode_dict.items():
        text = re.sub(pattern, replacement, text)

    # 3. Rút gọn ký tự lặp kéo dài (Ví dụ: đẹpppp -> đẹp)
    vietnamese_chars = "a-zàáạảãâầấậẩẫăằắặẳẵèéẹẻẽêềếệểễìíịỉĩòóọỏõôồốộổỗơờớợởỡùúụủũưừứựửữỳýỵỷỹđ"
    text = re.sub(r"([" + vietnamese_chars + r"])\1+", r"\1", text)

    # 4. Chuẩn hóa khoảng trắng
    text = re.sub(r"\s+", " ", text)
    return text.strip()

print("Quy trình xóa Emoji/Icon và Chuẩn hóa văn bản")

# Duyệt qua các tập dữ liệu đã được lọc rác ở Quy trình 1
for name, df_filtered in filtered_dataframes.items():
    # Áp dụng hàm làm sạch và tạo cột mới dữ liệu chuẩn
    df_filtered["Review_Cleaned"] = df_filtered["Review"].apply(
        clean_and_normalize_review
    )

    # Xuất bản file sạch hoàn toàn ra thư mục Colab
    output_filename = f"Shoes_{name}_Cleaned.csv"
    df_filtered.to_csv(output_filename, index=False, encoding="utf-8-sig")
    print(f" Hệ thống đã lưu file dữ liệu chuẩn hóa: {output_filename}")

# Bảng đối chiếu dữ liệu trước và sau khi xử lý
df_test_cleaned_view = filtered_dataframes["Test"].head(4)

print("\n Bảng đối chiếu dữ liệu trước và sau khi thực hiện quy trình:")
print(
    df_test_cleaned_view[["Review", "Review_Cleaned"]].to_markdown(index=True)
)